FROM node:18-bullseye AS build
WORKDIR /app

COPY WebPhotoIllustrator/package.json WebPhotoIllustrator/package-lock.json ./

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 make g++ && \
    rm -rf /var/lib/apt/lists/*

ENV DISABLE_ESLINT_PLUGIN=true
ENV TSC_COMPILE_ON_ERROR=true
ENV NODE_OPTIONS="--max-old-space-size=4096"

RUN npm ci --legacy-peer-deps --prefer-offline

COPY WebPhotoIllustrator/ .

RUN echo "declare module 'sebikostudio-icons';" > src/sebikostudio-icons.d.ts


RUN npm run build

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/build /usr/share/nginx/html
COPY Docker/ClientDocker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]